# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MIK8nfQzbmTY0htj7JpCTaxTSIMtikWM
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn import linear_model

df = pd.read_csv("/content/house-prices.csv")
df

df.dtypes

plt.scatter(df["area"], df["price"], color="gold")
plt.xlabel("Area (in Square Feet)")
plt.ylabel("Price (in $)")

reg_obj = linear_model.LinearRegression()
reg_obj.fit(df[["area"]], df["price"])

df2 = pd.DataFrame({"area": df["area"]})
df2

predicted_arr = reg_obj.predict(df2)

print(predicted_arr[:10], end=", ")
print("...", end=", ")
print(predicted_arr[-10:])

m = reg_obj.coef_ # ouputs the value of slope(m)
m

c = reg_obj.intercept_ # outputs the value of intercept(c)
c

x = df2.to_numpy(df["area"])

using_formula_arr = np.empty(1000)
for i in range(len(x)):
    using_formula_arr[i] = m * x[i] + c
#     print(m * x[i] + c, end=", ")

print(using_formula_arr[:10], end=", ")
print("...", end=", ")
print(using_formula_arr[-10:])

np.array_equal(predicted_arr, using_formula_arr)

df["predicted_price"] = predicted_arr
display(df)

plt.plot(df["area"], df["predicted_price"], color="red")
plt.scatter(df["area"], df["predicted_price"], color="lime")

plt.xlabel("Area (in Square Feet)")
plt.ylabel("Price (in $)")

plt.scatter(df["area"], df["price"], color="gold")
plt.plot(df["area"], df["predicted_price"], color="red")

plt.xlabel("Area (in Square Feet)")
plt.ylabel("Price (in $)")

display(df)
print(df.dtypes)